// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"

	"github.com/jackc/pgtype"
)

type IbentAplikasi struct {
	KodeAplikasi  string         `json:"kode_aplikasi"`
	NamaAplikasi  sql.NullString `json:"nama_aplikasi"`
	Deskripsi     sql.NullString `json:"deskripsi"`
	NamaServer    sql.NullString `json:"nama_server"`
	ProtokolAkses sql.NullString `json:"protokol_akses"`
	LokasiSource  sql.NullString `json:"lokasi_source"`
	LokasiSession sql.NullString `json:"lokasi_session"`
	NamaSession   sql.NullString `json:"nama_session"`
}

type IbentAppsubsystem struct {
	SubsystemCode  string         `json:"subsystem_code"`
	SubsystemName  sql.NullString `json:"subsystem_name"`
	IsLocal        sql.NullString `json:"is_local"`
	SessionName    sql.NullString `json:"session_name"`
	RemoteHost     sql.NullString `json:"remote_host"`
	RemotePort     sql.NullInt32  `json:"remote_port"`
	IsSsl          sql.NullString `json:"is_ssl"`
	SslProfileName sql.NullString `json:"ssl_profile_name"`
	RemoteAppid    sql.NullString `json:"remote_appid"`
	KodeAplikasi   sql.NullString `json:"kode_aplikasi"`
}

type IbentAreacabang struct {
	KodeWilayah      string         `json:"kode_wilayah"`
	Keterangan       sql.NullString `json:"keterangan"`
	TanggalInput     sql.NullTime   `json:"tanggal_input"`
	TanggalPerbarui  sql.NullTime   `json:"tanggal_perbarui"`
	TerminalInput    sql.NullString `json:"terminal_input"`
	TerminalPerbarui sql.NullString `json:"terminal_perbarui"`
	UserInput        sql.NullString `json:"user_input"`
	UserPerbarui     sql.NullString `json:"user_perbarui"`
	KodeWilayahInduk sql.NullString `json:"kode_wilayah_induk"`
}

type IbentBlobdatum struct {
	IDData int32          `json:"id_data"`
	Data   sql.NullString `json:"data"`
}

type IbentBpparallelstep struct {
	ParallelStepID int32          `json:"parallel_step_id"`
	ParameterName  sql.NullString `json:"parameter_name"`
	ParameterOrder sql.NullInt32  `json:"parameter_order"`
	ParameterType  sql.NullInt32  `json:"parameter_type"`
	StepID         sql.NullInt32  `json:"step_id"`
}

type IbentBpparallelstepdetail struct {
	PstepDetailID      int32          `json:"pstep_detail_id"`
	Svalue             sql.NullString `json:"svalue"`
	Ivalue             sql.NullInt32  `json:"ivalue"`
	ParameterType      sql.NullInt32  `json:"parameter_type"`
	UnrestrictNextStep sql.NullString `json:"unrestrict_next_step"`
	ParallelStepID     sql.NullInt32  `json:"parallel_step_id"`
	Disabled           sql.NullString `json:"disabled"`
}

type IbentBpparallelstepinstance struct {
	PstepinstID   int32         `json:"pstepinst_id"`
	StepinstID    sql.NullInt32 `json:"stepinst_id"`
	PstepDetailID sql.NullInt32 `json:"pstep_detail_id"`
}

type IbentBpprocess struct {
	BpprocessID int32          `json:"bpprocess_id"`
	Pid         sql.NullInt32  `json:"pid"`
	Status      sql.NullInt32  `json:"status"`
	MainPid     sql.NullInt32  `json:"main_pid"`
	Phost       sql.NullString `json:"phost"`
	ErrorInfo   sql.NullString `json:"error_info"`
	StepID      sql.NullInt32  `json:"step_id"`
	Ctlcommand  sql.NullInt32  `json:"ctlcommand"`
	Processed   sql.NullInt32  `json:"processed"`
}

type IbentBpscenario struct {
	ScenarioCode string         `json:"scenario_code"`
	ScenarioName sql.NullString `json:"scenario_name"`
}

type IbentBpscenariocollection struct {
	CollectionCode string         `json:"collection_code"`
	CollectionName sql.NullString `json:"collection_name"`
}

type IbentBpscenarioinstance struct {
	InstanceID   int32          `json:"instance_id"`
	StartTime    sql.NullTime   `json:"start_time"`
	StopTime     sql.NullTime   `json:"stop_time"`
	UserID       sql.NullString `json:"user_id"`
	TerminalID   sql.NullString `json:"terminal_id"`
	Status       sql.NullInt32  `json:"status"`
	MainPid      sql.NullInt32  `json:"main_pid"`
	ScenarioCode sql.NullString `json:"scenario_code"`
	ProcessDate  sql.NullTime   `json:"process_date"`
}

type IbentBpscenariostatus struct {
	IDPod        sql.NullInt32  `json:"id_pod"`
	LastScenario sql.NullString `json:"last_scenario"`
	LastProctime sql.NullTime   `json:"last_proctime"`
	LastStatus   sql.NullInt32  `json:"last_status"`
	LastErrinfo  sql.NullString `json:"last_errinfo"`
}

type IbentBpscollectionmember struct {
	MemberID       int32          `json:"member_id"`
	MemberOrder    pgtype.Numeric `json:"member_order"`
	ScenarioCode   sql.NullString `json:"scenario_code"`
	CollectionCode sql.NullString `json:"collection_code"`
}

type IbentBpscript struct {
	ScriptID     int32          `json:"script_id"`
	Description  sql.NullString `json:"description"`
	ScriptPath   sql.NullString `json:"script_path"`
	KodeAplikasi sql.NullString `json:"kode_aplikasi"`
}

type IbentBpstep struct {
	StepID       int32          `json:"step_id"`
	Description  sql.NullString `json:"description"`
	StepOrder    sql.NullInt32  `json:"step_order"`
	Disabled     sql.NullString `json:"disabled"`
	ScenarioCode sql.NullString `json:"scenario_code"`
	ScriptID     sql.NullInt32  `json:"script_id"`
}

type IbentBpstepinstance struct {
	StepinstID       int32          `json:"stepinst_id"`
	StartTime        sql.NullTime   `json:"start_time"`
	StopTime         sql.NullTime   `json:"stop_time"`
	Status           sql.NullInt32  `json:"status"`
	StepErrorMessage sql.NullString `json:"step_error_message"`
	MainPid          sql.NullInt32  `json:"main_pid"`
	Pid              sql.NullInt32  `json:"pid"`
	StepID           sql.NullInt32  `json:"step_id"`
	InstanceID       sql.NullInt32  `json:"instance_id"`
}

type IbentCabang struct {
	KodeCabang          string         `json:"kode_cabang"`
	NamaCabang          sql.NullString `json:"nama_cabang"`
	TipeCabang          sql.NullString `json:"tipe_cabang"`
	StatusCabang        sql.NullString `json:"status_cabang"`
	SandiBi             sql.NullString `json:"sandi_bi"`
	ZonaWaktu           sql.NullString `json:"zona_waktu"`
	UserInput           sql.NullString `json:"user_input"`
	TanggalInput        sql.NullTime   `json:"tanggal_input"`
	TerminalInput       sql.NullString `json:"terminal_input"`
	UserOtorisasi       sql.NullString `json:"user_otorisasi"`
	TanggalOtorisasi    sql.NullTime   `json:"tanggal_otorisasi"`
	TerminalOtorisasi   sql.NullString `json:"terminal_otorisasi"`
	KodeCabangInduk     sql.NullString `json:"kode_cabang_induk"`
	StatusAktif         sql.NullString `json:"status_aktif"`
	StatusOtorisasi     sql.NullString `json:"status_otorisasi"`
	KodeWilayah         sql.NullString `json:"kode_wilayah"`
	KodeKantor          sql.NullString `json:"kode_kantor"`
	KodeLokasi          sql.NullString `json:"kode_lokasi"`
	StatusAkses         sql.NullString `json:"status_akses"`
	KodeWilayahKliring  sql.NullString `json:"kode_wilayah_kliring"`
	LevelCaban          pgtype.Numeric `json:"level_caban"`
	LevelCabang         pgtype.Numeric `json:"level_cabang"`
	IDSandilokasi       sql.NullInt32  `json:"id_sandilokasi"`
	IDSandibi           sql.NullInt32  `json:"id_sandibi"`
	KantorAlamat        sql.NullString `json:"kantor_alamat"`
	KantorKodePos       sql.NullString `json:"kantor_kode_pos"`
	KantorNama          sql.NullString `json:"kantor_nama"`
	KantorNpwp          sql.NullString `json:"kantor_npwp"`
	KantorTelepon1      sql.NullString `json:"kantor_telepon1"`
	KantorTelepon2      sql.NullString `json:"kantor_telepon2"`
	KantorTelepon3      sql.NullString `json:"kantor_telepon3"`
	KantorTipe          sql.NullString `json:"kantor_tipe"`
	IsKordinatorKliring sql.NullString `json:"is_kordinator_kliring"`
	PejabatCabang       sql.NullString `json:"pejabat_cabang"`
	JabatanPejabat      sql.NullString `json:"jabatan_pejabat"`
	KantorKota          sql.NullString `json:"kantor_kota"`
	StatusBds           sql.NullString `json:"status_bds"`
}

type IbentCfgRefdatum struct {
	RefType    string         `json:"ref_type"`
	RefCode    string         `json:"ref_code"`
	RefDesc    sql.NullString `json:"ref_desc"`
	StatusData sql.NullString `json:"status_data"`
	IsLeaf     sql.NullString `json:"is_leaf"`
	CodeSlik   sql.NullString `json:"code_slik"`
	DescSlik   sql.NullString `json:"desc_slik"`
	CodeLsmk   sql.NullString `json:"code_lsmk"`
	DescLsmk   sql.NullString `json:"desc_lsmk"`
	CodeLbus   sql.NullString `json:"code_lbus"`
	DescLbus   sql.NullString `json:"desc_lbus"`
	CodeAnta   sql.NullString `json:"code_anta"`
	DescAnta   sql.NullString `json:"desc_anta"`
}

type IbentCfgReftype struct {
	RefType     string         `json:"ref_type"`
	Description string         `json:"description"`
	DefCode     sql.NullString `json:"def_code"`
}

type IbentCrewpayroll struct {
	NomorRekening string          `json:"nomor_rekening"`
	NilaiMutasi   sql.NullFloat64 `json:"nilai_mutasi"`
	Keterangan    sql.NullString  `json:"keterangan"`
}

type IbentDeparteman struct {
	KodeDepartemen   string         `json:"kode_departemen"`
	NamaDepartemen   sql.NullString `json:"nama_departemen"`
	Deskripsi        sql.NullString `json:"deskripsi"`
	StatusAktif      sql.NullString `json:"status_aktif"`
	UserInput        sql.NullString `json:"user_input"`
	TanggalInput     sql.NullTime   `json:"tanggal_input"`
	TerminalInput    sql.NullString `json:"terminal_input"`
	UserPerbarui     sql.NullString `json:"user_perbarui"`
	TanggalPerbarui  sql.NullTime   `json:"tanggal_perbarui"`
	TerminalPerbarui sql.NullString `json:"terminal_perbarui"`
	TipeAkses        sql.NullString `json:"tipe_akses"`
}

type IbentEmployee struct {
	NomorKaryawan         string         `json:"nomor_karyawan"`
	NamaLengkap           sql.NullString `json:"nama_lengkap"`
	Alamat                sql.NullString `json:"alamat"`
	KodePos               sql.NullString `json:"kode_pos"`
	NomorTelepon          sql.NullString `json:"nomor_telepon"`
	NomorSeluler          sql.NullString `json:"nomor_seluler"`
	NamaSupervisor        sql.NullString `json:"nama_supervisor"`
	IsSupervisor          sql.NullString `json:"is_supervisor"`
	IsPersonalia          sql.NullString `json:"is_personalia"`
	IsLemburberlaku       sql.NullString `json:"is_lemburberlaku"`
	NomorKartu            sql.NullString `json:"nomor_kartu"`
	KodeCabang            sql.NullString `json:"kode_cabang"`
	KodeDepartemen        sql.NullString `json:"kode_departemen"`
	KodeJabatan           sql.NullString `json:"kode_jabatan"`
	StatusAktif           sql.NullString `json:"status_aktif"`
	UserInput             sql.NullString `json:"user_input"`
	TanggalInput          sql.NullTime   `json:"tanggal_input"`
	TerminalInput         sql.NullString `json:"terminal_input"`
	UserPerbarui          sql.NullString `json:"user_perbarui"`
	TanggalPerbarui       sql.NullTime   `json:"tanggal_perbarui"`
	TerminalPerbarui      sql.NullString `json:"terminal_perbarui"`
	FingerstationTerminal sql.NullString `json:"fingerstation_terminal"`
	KodeKantor            sql.NullString `json:"kode_kantor"`
}

type IbentEnumInt struct {
	EnumName        string         `json:"enum_name"`
	EnumValue       int32          `json:"enum_value"`
	EnumDescription sql.NullString `json:"enum_description"`
}

type IbentEnumVarchar struct {
	EnumName        string         `json:"enum_name"`
	EnumValue       string         `json:"enum_value"`
	EnumDescription sql.NullString `json:"enum_description"`
}

type IbentExecutablefungsi struct {
	IsDualControl          sql.NullString  `json:"is_dual_control"`
	LevelDualControl       sql.NullInt32   `json:"level_dual_control"`
	LevelOverride          sql.NullInt32   `json:"level_override"`
	LevelAkses             sql.NullInt32   `json:"level_akses"`
	HariDiperbolehkanAkses sql.NullString  `json:"hari_diperbolehkan_akses"`
	WaktuBolehDiakses      sql.NullTime    `json:"waktu_boleh_diakses"`
	WaktuSelesaiDiakses    sql.NullTime    `json:"waktu_selesai_diakses"`
	IDFungsi               string          `json:"id_fungsi"`
	RestriksiHariAkses     sql.NullString  `json:"restriksi_hari_akses"`
	RestriksiWaktuAkses    sql.NullString  `json:"restriksi_waktu_akses"`
	LimitTransaksiUser     sql.NullFloat64 `json:"limit_transaksi_user"`
}

type IbentFaTtran struct {
	Mstype sql.NullString `json:"mstype"`
	Nrekgl sql.NullString `json:"nrekgl"`
	Nocabg sql.NullString `json:"nocabg"`
	Kdvalt sql.NullString `json:"kdvalt"`
	Respct sql.NullString `json:"respct"`
	Kdtrex sql.NullString `json:"kdtrex"`
	Kdmnem sql.NullString `json:"kdmnem"`
	Tgltra sql.NullTime   `json:"tgltra"`
	Norefs sql.NullString `json:"norefs"`
	Jumtra pgtype.Numeric `json:"jumtra"`
	Userid sql.NullString `json:"userid"`
	Overid sql.NullString `json:"overid"`
	Otorid sql.NullString `json:"otorid"`
	Kettra sql.NullString `json:"kettra"`
	Kettr2 sql.NullString `json:"kettr2"`
	Nbatch sql.NullString `json:"nbatch"`
	Messid sql.NullString `json:"messid"`
	Kodapl interface{}    `json:"kodapl"`
	Salawl pgtype.Numeric `json:"salawl"`
}

type IbentFingerstation struct {
	FingerstationID int32          `json:"fingerstation_id"`
	KodeCabang      sql.NullString `json:"kode_cabang"`
	IDTerminal      sql.NullString `json:"id_terminal"`
}

type IbentFungsi struct {
	IDFungsi       string         `json:"id_fungsi"`
	NamaFungsi     sql.NullString `json:"nama_fungsi"`
	TipeFungsi     sql.NullString `json:"tipe_fungsi"`
	IDParentFungsi sql.NullString `json:"id_parent_fungsi"`
	KodeAplikasi   sql.NullString `json:"kode_aplikasi"`
}

type IbentGlinterface struct {
	KodeInterface    sql.NullString `json:"kode_interface"`
	TipeInterface    sql.NullString `json:"tipe_interface"`
	KodeAccount      sql.NullString `json:"kode_account"`
	KodeRc           sql.NullString `json:"kode_rc"`
	Deskripsi        sql.NullString `json:"deskripsi"`
	UserInput        sql.NullString `json:"user_input"`
	TanggalInput     sql.NullTime   `json:"tanggal_input"`
	TerminalInput    sql.NullString `json:"terminal_input"`
	UserPerbarui     sql.NullString `json:"user_perbarui"`
	TanggalPerbarui  sql.NullTime   `json:"tanggal_perbarui"`
	TerminalPerbarui sql.NullString `json:"terminal_perbarui"`
	IDInterface      int32          `json:"id_interface"`
	KodeValuta       sql.NullString `json:"kode_valuta"`
	KodeCabang       sql.NullString `json:"kode_cabang"`
}

type IbentHistorikehadiran struct {
	Tanggal            sql.NullTime   `json:"tanggal"`
	IDHistoriKehadiran int32          `json:"id_histori_kehadiran"`
	WaktuDatang        sql.NullTime   `json:"waktu_datang"`
	WaktuPulang        sql.NullTime   `json:"waktu_pulang"`
	NamaCabang         sql.NullString `json:"nama_cabang"`
	NamaDepartemen     sql.NullString `json:"nama_departemen"`
	NomorKaryawan      sql.NullString `json:"nomor_karyawan"`
	IpDatang           sql.NullString `json:"ip_datang"`
	IpPulang           sql.NullString `json:"ip_pulang"`
}

type IbentIDGen struct {
	IDCode string         `json:"id_code"`
	LastID sql.NullInt32  `json:"last_id"`
	Locked sql.NullString `json:"locked"`
}

type IbentInbox struct {
	Cabang        sql.NullString  `json:"cabang"`
	Deskripsi     sql.NullString  `json:"deskripsi"`
	GrupUser      sql.NullString  `json:"grup_user"`
	IDInbox       int32           `json:"id_inbox"`
	Inputer       sql.NullString  `json:"inputer"`
	IsTerproses   sql.NullString  `json:"is_terproses"`
	LevelUser     sql.NullInt32   `json:"level_user"`
	Limit         sql.NullFloat64 `json:"limit"`
	NamaFile      sql.NullString  `json:"nama_file"`
	Status        sql.NullString  `json:"status"`
	ParameterCode sql.NullString  `json:"parameter_code"`
}

type IbentInboxparameter struct {
	ParameterCode  string         `json:"parameter_code"`
	Description    sql.NullString `json:"description"`
	ParameterType  sql.NullString `json:"parameter_type"`
	FormScriptName sql.NullString `json:"form_script_name"`
	IDFungsi       sql.NullString `json:"id_fungsi"`
}

type IbentJabatan struct {
	KodeJabatan string         `json:"kode_jabatan"`
	NamaJabatan sql.NullString `json:"nama_jabatan"`
	Deskripsi   sql.NullString `json:"deskripsi"`
}

type IbentKantor struct {
	KodeKantor    string         `json:"kode_kantor"`
	NamaKantor    sql.NullString `json:"nama_kantor"`
	TipeKantor    sql.NullString `json:"tipe_kantor"`
	Alamat        sql.NullString `json:"alamat"`
	NomorNpwp     sql.NullString `json:"nomor_npwp"`
	KodePos       sql.NullString `json:"kode_pos"`
	NomorTelepon1 sql.NullString `json:"nomor_telepon1"`
	NomorTelepon2 sql.NullString `json:"nomor_telepon2"`
	NomorTelepon3 sql.NullString `json:"nomor_telepon3"`
	KodeCabang    sql.NullString `json:"kode_cabang"`
}

type IbentLastobjauditdatum struct {
	LastauditID int32          `json:"lastaudit_id"`
	ParamID     sql.NullInt32  `json:"param_id"`
	DatakeyInt  sql.NullInt32  `json:"datakey_int"`
	DatakeyStr  sql.NullString `json:"datakey_str"`
	AuditID     sql.NullInt32  `json:"audit_id"`
}

type IbentLimitoperasi struct {
	IDLimitOperasi      int32           `json:"id_limit_operasi"`
	JenisLimit          sql.NullString  `json:"jenis_limit"`
	NilaiLimit          sql.NullFloat64 `json:"nilai_limit"`
	NilaiLimitAkumulasi sql.NullFloat64 `json:"nilai_limit_akumulasi"`
	JumlahItemLimit     sql.NullInt32   `json:"jumlah_item_limit"`
	StatusOtorisasi     sql.NullString  `json:"status_otorisasi"`
	KodeCabang          sql.NullString  `json:"kode_cabang"`
}

type IbentLimittransaksi struct {
	IDLimitTransaksi    int32           `json:"id_limit_transaksi"`
	JenisLimit          sql.NullString  `json:"jenis_limit"`
	NilaiLimit          sql.NullFloat64 `json:"nilai_limit"`
	NilaiLimitAkumulasi sql.NullFloat64 `json:"nilai_limit_akumulasi"`
	JumlahItemLimit     sql.NullInt32   `json:"jumlah_item_limit"`
	IDUser              sql.NullString  `json:"id_user"`
}

type IbentListaplikasiperan struct {
	KodeAplikasi string `json:"kode_aplikasi"`
	IDPeran      string `json:"id_peran"`
}

type IbentListaplikasiuser struct {
	IDListaplikasiuser int32          `json:"id_listaplikasiuser"`
	IDUser             sql.NullString `json:"id_user"`
	KodeAplikasi       sql.NullString `json:"kode_aplikasi"`
}

type IbentListareadiizinkan struct {
	IDUser      string `json:"id_user"`
	KodeWilayah string `json:"kode_wilayah"`
}

type IbentListcabangdiizinkan struct {
	IDUser     string `json:"id_user"`
	KodeCabang string `json:"kode_cabang"`
}

type IbentListdepartemendiizinkan struct {
	NomorKaryawan  string `json:"nomor_karyawan"`
	KodeDepartemen string `json:"kode_departemen"`
}

type IbentListfungsiaplikasiperan struct {
	KodeAplikasi string `json:"kode_aplikasi"`
	IDPeran      string `json:"id_peran"`
	IDFungsi     string `json:"id_fungsi"`
}

type IbentListfungsiaplikasiuser struct {
	IDListfungsiaplikasiuser int32          `json:"id_listfungsiaplikasiuser"`
	IDFungsi                 sql.NullString `json:"id_fungsi"`
	IDListaplikasiuser       sql.NullInt32  `json:"id_listaplikasiuser"`
}

type IbentListperanuser struct {
	IDPeran        string        `json:"id_peran"`
	IDUser         string        `json:"id_user"`
	LevelPeranuser sql.NullInt32 `json:"level_peranuser"`
}

type IbentListterminaldiizinkan struct {
	IDUser     string `json:"id_user"`
	IDTerminal string `json:"id_terminal"`
}

type IbentLoginsession struct {
	LoginID        int32          `json:"login_id"`
	IDUser         sql.NullString `json:"id_user"`
	LoginTime      sql.NullTime   `json:"login_time"`
	TerminalIp     sql.NullString `json:"terminal_ip"`
	AppID          sql.NullString `json:"app_id"`
	SessionID      sql.NullString `json:"session_id"`
	LastAccessTime sql.NullTime   `json:"last_access_time"`
	BranchCode     sql.NullString `json:"branch_code"`
	UserID         sql.NullString `json:"user_id"`
}

type IbentLokasi struct {
	KodeLokasi string         `json:"kode_lokasi"`
	NamaLokasi sql.NullString `json:"nama_lokasi"`
	StatusData sql.NullString `json:"status_data"`
}

type IbentMenu struct {
	MenuID       int32          `json:"menu_id"`
	MenuName     sql.NullString `json:"menu_name"`
	Caption      sql.NullString `json:"caption"`
	MenuLevel    pgtype.Numeric `json:"menu_level"`
	ParentID     sql.NullInt32  `json:"parent_id"`
	IsMainMenu   sql.NullString `json:"is_main_menu"`
	MenuIdx      sql.NullString `json:"menu_idx"`
	FilenameID   sql.NullString `json:"filename_id"`
	IsPopupMenu  sql.NullString `json:"is_popup_menu"`
	KodeAplikasi sql.NullString `json:"kode_aplikasi"`
	MenuType     sql.NullString `json:"menu_type"`
}

type IbentMenuhierarchy struct {
	HierarchyID int32         `json:"hierarchy_id"`
	ParentID    sql.NullInt32 `json:"parent_id"`
	ChildID     sql.NullInt32 `json:"child_id"`
}

type IbentObjevent struct {
	EventID     int32          `json:"event_id"`
	EvtclassID  int32          `json:"evtclass_id"`
	EventCode   sql.NullString `json:"event_code"`
	Description sql.NullString `json:"description"`
}

type IbentObjeventclass struct {
	EvtclassID  int32          `json:"evtclass_id"`
	Classname   sql.NullString `json:"classname"`
	Description sql.NullString `json:"description"`
}

type IbentObjeventproc struct {
	InstanceID  int32          `json:"instance_id"`
	EventID     int32          `json:"event_id"`
	ScriptID    sql.NullString `json:"script_id"`
	Description sql.NullString `json:"description"`
	SessionID   sql.NullString `json:"session_id"`
}

type IbentOtordatum struct {
	IDData         int32          `json:"id_data"`
	Actualfilename sql.NullString `json:"actualfilename"`
	IsDataPacket   sql.NullString `json:"is_data_packet"`
	ClobData       sql.NullString `json:"clob_data"`
}

type IbentOtorentri struct {
	IDOtorisasi       int32          `json:"id_otorisasi"`
	TglInput          sql.NullTime   `json:"tgl_input"`
	KodeEntri         sql.NullString `json:"kode_entri"`
	UserInput         sql.NullString `json:"user_input"`
	TerminalInput     sql.NullString `json:"terminal_input"`
	TipeTarget        sql.NullInt32  `json:"tipe_target"`
	Keterangan        sql.NullString `json:"keterangan"`
	Info1             sql.NullString `json:"info1"`
	Info2             sql.NullString `json:"info2"`
	IDUser            sql.NullString `json:"id_user"`
	IDPeran           sql.NullString `json:"id_peran"`
	KodeCabang        sql.NullString `json:"kode_cabang"`
	IDData            sql.NullInt32  `json:"id_data"`
	IDData1           sql.NullInt32  `json:"id_data1"`
	NamaTabel         sql.NullString `json:"nama_tabel"`
	TipeKey           sql.NullInt32  `json:"tipe_key"`
	KeyInt            sql.NullInt32  `json:"key_int"`
	KeyString         sql.NullString `json:"key_string"`
	TglValuta         sql.NullTime   `json:"tgl_valuta"`
	TransactionAmount pgtype.Numeric `json:"transaction_amount"`
	OverrideState     sql.NullString `json:"override_state"`
	UserOverride      sql.NullString `json:"user_override"`
	AddInfo           sql.NullString `json:"add_info"`
}

type IbentOtorentrihistori struct {
	IDOtorisasi       int32          `json:"id_otorisasi"`
	TglInput          sql.NullTime   `json:"tgl_input"`
	KodeEntri         sql.NullString `json:"kode_entri"`
	UserInput         sql.NullString `json:"user_input"`
	TerminalInput     sql.NullString `json:"terminal_input"`
	TipeTarget        sql.NullInt32  `json:"tipe_target"`
	TglOtorisasi      sql.NullTime   `json:"tgl_otorisasi"`
	UserOtorisasi     sql.NullString `json:"user_otorisasi"`
	TerminalOtorisasi sql.NullString `json:"terminal_otorisasi"`
	StatusOtorisasi   sql.NullString `json:"status_otorisasi"`
	Keterangan        sql.NullString `json:"keterangan"`
	Info1             sql.NullString `json:"info1"`
	Info2             sql.NullString `json:"info2"`
	IDData            sql.NullInt32  `json:"id_data"`
	IDUser            sql.NullString `json:"id_user"`
	IDPeran           sql.NullString `json:"id_peran"`
	KodeCabang        sql.NullString `json:"kode_cabang"`
	IDData1           sql.NullInt32  `json:"id_data1"`
	NamaEntri         sql.NullString `json:"nama_entri"`
	NamaTabel         sql.NullString `json:"nama_tabel"`
	TipeKey           sql.NullInt32  `json:"tipe_key"`
	KeyInt            sql.NullInt32  `json:"key_int"`
	KeyString         sql.NullString `json:"key_string"`
	TglValuta         sql.NullTime   `json:"tgl_valuta"`
	UserOverride      sql.NullString `json:"user_override"`
	AddInfo           sql.NullString `json:"add_info"`
}

type IbentOtorobject struct {
	KodeObject    string         `json:"kode_object"`
	Keterangan    sql.NullString `json:"keterangan"`
	NamaTabelCari sql.NullString `json:"nama_tabel_cari"`
}

type IbentOtorparameter struct {
	KodeEntri       string         `json:"kode_entri"`
	RemoteFormID    sql.NullString `json:"remote_form_id"`
	MethodIDSave    sql.NullString `json:"method_id_save"`
	SubsystemCode   sql.NullString `json:"subsystem_code"`
	MethodIDReject  sql.NullString `json:"method_id_reject"`
	NamaEntri       sql.NullString `json:"nama_entri"`
	ClassicFormCall sql.NullString `json:"classic_form_call"`
	KodeObject      sql.NullString `json:"kode_object"`
}

type IbentOtorparameterperan struct {
	IDOtorparameterperan int32          `json:"id_otorparameterperan"`
	IDPeran              sql.NullString `json:"id_peran"`
	KodeEntri            sql.NullString `json:"kode_entri"`
	Status               sql.NullString `json:"status"`
	TerminalInput        sql.NullString `json:"terminal_input"`
	TerminalPerbarui     sql.NullString `json:"terminal_perbarui"`
	UserInput            sql.NullString `json:"user_input"`
	UserPerbarui         sql.NullString `json:"user_perbarui"`
	TanggalInput         sql.NullTime   `json:"tanggal_input"`
	TanggalPerbarui      sql.NullTime   `json:"tanggal_perbarui"`
}

type IbentOtpkey struct {
	Userid     string         `json:"userid"`
	TokenBase  sql.NullString `json:"token_base"`
	TChallenge sql.NullTime   `json:"t_challenge"`
	Key1       sql.NullInt32  `json:"key1"`
	Key2       sql.NullInt32  `json:"key2"`
	Key3       sql.NullInt32  `json:"key3"`
	Key4       sql.NullInt32  `json:"key4"`
	Key5       sql.NullInt32  `json:"key5"`
}

type IbentParameterglobal struct {
	KodeParameter         string          `json:"kode_parameter"`
	TipeParameter         sql.NullString  `json:"tipe_parameter"`
	NilaiParameter        sql.NullFloat64 `json:"nilai_parameter"`
	Deskripsi             sql.NullString  `json:"deskripsi"`
	IsParameterSystem     sql.NullString  `json:"is_parameter_system"`
	NilaiParameterTanggal sql.NullTime    `json:"nilai_parameter_tanggal"`
	NilaiParameterString  sql.NullString  `json:"nilai_parameter_string"`
	Status                sql.NullString  `json:"status"`
}

type IbentPeran struct {
	IDPeran          string         `json:"id_peran"`
	NamaPeran        sql.NullString `json:"nama_peran"`
	Deskripsi        sql.NullString `json:"deskripsi"`
	UserInput        sql.NullString `json:"user_input"`
	TanggalInput     sql.NullTime   `json:"tanggal_input"`
	TerminalInput    sql.NullString `json:"terminal_input"`
	UserPerbarui     sql.NullString `json:"user_perbarui"`
	TanggalPerbarui  sql.NullTime   `json:"tanggal_perbarui"`
	TerminalPerbarui sql.NullString `json:"terminal_perbarui"`
	StatusPeran      sql.NullString `json:"status_peran"`
	KategoriPeran    sql.NullString `json:"kategori_peran"`
}

type IbentPublication struct {
	PublicationCode string         `json:"publication_code"`
	Description     sql.NullString `json:"description"`
}

type IbentReferenceLimit struct {
	ID                  int32           `json:"id"`
	GroupLimit          sql.NullString  `json:"group_limit"`
	JenisLimit          sql.NullString  `json:"jenis_limit"`
	NilaiLimit          sql.NullFloat64 `json:"nilai_limit"`
	NilaiLimitAkumulasi sql.NullFloat64 `json:"nilai_limit_akumulasi"`
	JumlahItemLimit     sql.NullInt32   `json:"jumlah_item_limit"`
}

type IbentReferenceMapLimit struct {
	ID            int32          `json:"id"`
	RolecodeHrmis sql.NullString `json:"rolecode_hrmis"`
	GroupLimit    sql.NullString `json:"group_limit"`
}

type IbentReferenceMapRole struct {
	ID            int32          `json:"id"`
	RolecodeHrmis sql.NullString `json:"rolecode_hrmis"`
	RolecodeIhsan sql.NullString `json:"rolecode_ihsan"`
}

type IbentReferencedatum struct {
	RefdataID       int32          `json:"refdata_id"`
	ReftypeID       int32          `json:"reftype_id"`
	ReferenceCode   string         `json:"reference_code"`
	ReferenceDesc   sql.NullString `json:"reference_desc"`
	ParentrefdataID sql.NullInt32  `json:"parentrefdata_id"`
	IsLeaf          sql.NullString `json:"is_leaf"`
	ReferenceLevel  sql.NullInt32  `json:"reference_level"`
	StatusData      sql.NullString `json:"status_data"`
}

type IbentReferencehierarchy struct {
	RefhierarchyID  int32 `json:"refhierarchy_id"`
	ParentrefdataID int32 `json:"parentrefdata_id"`
	ChildrefdataID  int32 `json:"childrefdata_id"`
}

type IbentReferencemap struct {
	RefmapID      int32          `json:"refmap_id"`
	RefmapType    sql.NullString `json:"refmap_type"`
	RefmapdefID   int32          `json:"refmapdef_id"`
	DestrefdataID int32          `json:"destrefdata_id"`
	SrcrefdataID  sql.NullInt32  `json:"srcrefdata_id"`
	IntkeySrc     sql.NullInt32  `json:"intkey_src"`
	StrkeySrc     sql.NullString `json:"strkey_src"`
}

type IbentReferencemapdef struct {
	RefmapdefID   int32          `json:"refmapdef_id"`
	Refmaptype    string         `json:"refmaptype"`
	Description   sql.NullString `json:"description"`
	DestreftypeID int32          `json:"destreftype_id"`
	SrcreftypeID  sql.NullInt32  `json:"srcreftype_id"`
	SrcClassname  sql.NullString `json:"src_classname"`
	SrcKeyname    sql.NullString `json:"src_keyname"`
	SrcKeytype    sql.NullInt32  `json:"src_keytype"`
}

type IbentReferencetype struct {
	ReftypeID       int32          `json:"reftype_id"`
	ReferenceName   sql.NullString `json:"reference_name"`
	Description     sql.NullString `json:"description"`
	KodeMapKategori sql.NullString `json:"kode_map_kategori"`
}

type IbentRefmapitem struct {
	KodeKategori string         `json:"kode_kategori"`
	SandiLbus    string         `json:"sandi_lbus"`
	SandiLsmk    string         `json:"sandi_lsmk"`
	SandiSid     string         `json:"sandi_sid"`
	StatusData   sql.NullString `json:"status_data"`
}

type IbentRefmapkategori struct {
	KodeKategori string         `json:"kode_kategori"`
	NamaKategori sql.NullString `json:"nama_kategori"`
	KolomDetil   sql.NullString `json:"kolom_detil"`
}

type IbentRefmapreport struct {
	KodeMapKategori sql.NullString `json:"kode_map_kategori"`
	ReftypeID       int32          `json:"reftype_id"`
	ReportType      sql.NullString `json:"report_type"`
}

type IbentRolemenulist struct {
	ListID  int32          `json:"list_id"`
	IDPeran sql.NullString `json:"id_peran"`
	MenuID  sql.NullInt32  `json:"menu_id"`
}

type IbentSalcrewpayroll struct {
	NomorRekening string          `json:"nomor_rekening"`
	Salsek        sql.NullFloat64 `json:"salsek"`
	Salseh        sql.NullFloat64 `json:"salseh"`
}

type IbentSubscribeitem struct {
	IDSitem         int32          `json:"id_sitem"`
	ScriptPath      sql.NullString `json:"script_path"`
	KodeAplikasi    sql.NullString `json:"kode_aplikasi"`
	PublicationCode sql.NullString `json:"publication_code"`
}

type IbentTeller struct {
	KodeRekeningTeller sql.NullString `json:"kode_rekening_teller"`
	IDUser             string         `json:"id_user"`
}

type IbentTerminal struct {
	IDTerminal       string         `json:"id_terminal"`
	NamaTerminal     sql.NullString `json:"nama_terminal"`
	LokasiTerminal   sql.NullString `json:"lokasi_terminal"`
	Deskripsi        sql.NullString `json:"deskripsi"`
	UserInput        sql.NullString `json:"user_input"`
	TanggalInput     sql.NullTime   `json:"tanggal_input"`
	TerminalInput    sql.NullString `json:"terminal_input"`
	UserPerbarui     sql.NullString `json:"user_perbarui"`
	TanggalPerbarui  sql.NullTime   `json:"tanggal_perbarui"`
	TerminalPerbarui sql.NullString `json:"terminal_perbarui"`
	KodeKantor       sql.NullString `json:"kode_kantor"`
	KodeCabang       sql.NullString `json:"kode_cabang"`
}

type IbentUserapp struct {
	IDUser                      string         `json:"id_user"`
	Password                    sql.NullString `json:"password"`
	StatusProfil                sql.NullString `json:"status_profil"`
	LevelUser                   sql.NullInt32  `json:"level_user"`
	TanggalDidaftarkan          sql.NullTime   `json:"tanggal_didaftarkan"`
	TanggalKadaluarsa           sql.NullTime   `json:"tanggal_kadaluarsa"`
	TanggalPasswordKadaluarsa   sql.NullTime   `json:"tanggal_password_kadaluarsa"`
	TanggalUbahPasswordTerakhir sql.NullTime   `json:"tanggal_ubah_password_terakhir"`
	TanggalAktifTerakhir        sql.NullTime   `json:"tanggal_aktif_terakhir"`
	TipeAksesCabang             sql.NullString `json:"tipe_akses_cabang"`
	TipeAksesTerminal           sql.NullString `json:"tipe_akses_terminal"`
	HariDiperbolehkanAkses      sql.NullString `json:"hari_diperbolehkan_akses"`
	StatusRestriksiWaktu        sql.NullString `json:"status_restriksi_waktu"`
	WaktuBolehMulai             sql.NullTime   `json:"waktu_boleh_mulai"`
	WaktuHarusSelesai           sql.NullTime   `json:"waktu_harus_selesai"`
	MaksimumJumlahLogin         sql.NullInt32  `json:"maksimum_jumlah_login"`
	UserInput                   sql.NullString `json:"user_input"`
	TanggalInput                sql.NullTime   `json:"tanggal_input"`
	TerminalInput               sql.NullString `json:"terminal_input"`
	UserPerbarui                sql.NullString `json:"user_perbarui"`
	TanggalPerbarui             sql.NullTime   `json:"tanggal_perbarui"`
	TerminalPerbarui            sql.NullString `json:"terminal_perbarui"`
	TipeUser                    sql.NullString `json:"tipe_user"`
	JumlahLoginGagal            sql.NullInt32  `json:"jumlah_login_gagal"`
	JumlahLoginAktif            sql.NullInt32  `json:"jumlah_login_aktif"`
	KunciAkses                  sql.NullString `json:"kunci_akses"`
	NamaUser                    sql.NullString `json:"nama_user"`
	JumlahValidasiGagal         sql.NullInt32  `json:"jumlah_validasi_gagal"`
	StatusPassword              sql.NullInt32  `json:"status_password"`
	MaksimumTidakAktif          sql.NullInt32  `json:"maksimum_tidak_aktif"`
	MaksimumGantiPassword       sql.NullInt32  `json:"maksimum_ganti_password"`
	NoUrutTeller                sql.NullString `json:"no_urut_teller"`
	IDTerminal                  sql.NullString `json:"id_terminal"`
	KodeCabang                  sql.NullString `json:"kode_cabang"`
	NomorKaryawan               sql.NullString `json:"nomor_karyawan"`
	MaksimumGagalLogin          pgtype.Numeric `json:"maksimum_gagal_login"`
	StatusAkses                 sql.NullString `json:"status_akses"`
	TipeLogin                   sql.NullString `json:"tipe_login"`
	FingerstationTerminal       sql.NullString `json:"fingerstation_terminal"`
	KodeKantor                  sql.NullString `json:"kode_kantor"`
}

type IbentUseraudit struct {
	AuditID          int32          `json:"audit_id"`
	UserID           string         `json:"user_id"`
	AppID            sql.NullString `json:"app_id"`
	TerminalIp       sql.NullString `json:"terminal_ip"`
	OperationCode    sql.NullString `json:"operation_code"`
	EventTime        sql.NullTime   `json:"event_time"`
	EventDescription sql.NullString `json:"event_description"`
	Info1            sql.NullString `json:"info1"`
	Info2            sql.NullString `json:"info2"`
}

type IbentUseraudithistori struct {
	AuditID          int32          `json:"audit_id"`
	UserID           string         `json:"user_id"`
	AppID            sql.NullString `json:"app_id"`
	TerminalIp       sql.NullString `json:"terminal_ip"`
	OperationCode    sql.NullString `json:"operation_code"`
	EventTime        sql.NullTime   `json:"event_time"`
	EventDescription sql.NullString `json:"event_description"`
	Info1            sql.NullString `json:"info1"`
	Info2            sql.NullString `json:"info2"`
}

type IbentUserbiodatum struct {
	IDBiodata     int32          `json:"id_biodata"`
	IDData        int32          `json:"id_data"`
	IDUser        sql.NullString `json:"id_user"`
	DataTag       string         `json:"data_tag"`
	Description   sql.NullString `json:"description"`
	NomorKaryawan sql.NullString `json:"nomor_karyawan"`
}

type IbentUsermenulist struct {
	ListID int32          `json:"list_id"`
	IDUser sql.NullString `json:"id_user"`
	MenuID sql.NullInt32  `json:"menu_id"`
}

type IbentUsersession struct {
	IDSession      int32          `json:"id_session"`
	SessionStamp   sql.NullString `json:"session_stamp"`
	IDUser         sql.NullString `json:"id_user"`
	LoginTime      sql.NullTime   `json:"login_time"`
	LogoutTime     sql.NullTime   `json:"logout_time"`
	LastAccessTime sql.NullTime   `json:"last_access_time"`
	Status         sql.NullString `json:"status"`
	IpUser         sql.NullString `json:"ip_user"`
	AppID          sql.NullString `json:"app_id"`
}

type IbentUsertbl struct {
	Userid       string         `json:"userid"`
	EncPassword1 sql.NullString `json:"enc_password1"`
	EncPassword2 sql.NullString `json:"enc_password2"`
}

type IbentWilayahkliring struct {
	KodeWilayahKliring string         `json:"kode_wilayah_kliring"`
	NamaWilayahKliring sql.NullString `json:"nama_wilayah_kliring"`
	Keterangan         sql.NullString `json:"keterangan"`
	HariEfektifKliring pgtype.Numeric `json:"hari_efektif_kliring"`
}
