// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateNewDataWilayah(ctx context.Context, arg CreateNewDataWilayahParams) (IbentAreacabang, error)
	DeleteWilayahByKodeWilayah(ctx context.Context, kodeWilayah string) ([]IbentAreacabang, error)
	GetDetilWilayahByKodeWilayah(ctx context.Context, kodeWilayah string) ([]IbentAreacabang, error)
	GetListWilayah(ctx context.Context) ([]IbentAreacabang, error)
	UpdateWilayahByKodeWilayah(ctx context.Context, arg UpdateWilayahByKodeWilayahParams) ([]IbentAreacabang, error)
}

var _ Querier = (*Queries)(nil)
